# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
