# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170415_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
